### ISSUE TITLE
Feature request: more data sources

### ISSUE THREAD

**Issue by megakoresh** [PaloAltoNetworks/terraform-provider-panos#104]
There are very few data sources available in the plugin atm. Things I would like to be able to pull from firewalls:

- interface information
  - static IPs
  - subinterfaces(preferably populated with same data)
  - security zones
  - virtual router
  - up/down state
  - anything else that is relevant
- nat rule (by name)
- security policy (by name)
- address objects
- service objects

The first one is probably the most important to me at the moment, but in general there is a surprising lack of data sources in this provider, considering most VFW appliances come with some stuff pre-configured, so its not like the entire configuration can be done from terraform with all variables known.

**Comment by ryanpodonnell1** [comment]
I would like to add this as well especially for panorama

```terraform
data "panos_panorama_registered_devices" "panorama" {}
```

attributes:
* serial_numbers
* firewall_versions
* vsys
* mgmt interface
* sync status
* connection status 
etc

basically whatever you would find on `panorama/managed-devices/summary`

**Comment by shinmog** [comment]
Numerous data sources have been added to the 1.7.0 provider, so I'm going to close this issue out.  Data sources for existing resources will be added gradually as existing resources get the `panos_address_object` treatment.

@ryanpodonnell1 @megakoresh 

If you have in mind a specific data source you want, please open a github issue for it so it can be tracked / addressed.
