### ISSUE TITLE
Attribute Documentation 

### ISSUE THREAD

**Issue by jonshern** [PaloAltoNetworks/terraform-provider-panos#221]
Most of the Terraform Documentation has a section for Attributes
Example: https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#attributes-reference

The documentation for many of the Palo Alto Resources have to attributes defined.
Please add this section so we can use the returned values.

**Comment by shinmog** [comment]
The panos provider doesn't have many `Computed: true` params.  There are a few places, but those are documented, and mostly everything is something that can be configured by the user.

**Comment by shinmog** [comment]
Data sources have been added to the v1.7.0 provider, and correctly document their attributes.  So I'm closing this issue.  More will be added as existing resources are retrofitted.
