### ISSUE TITLE
Commit documentation broken

### ISSUE THREAD

**Issue by stobias123** [PaloAltoNetworks/terraform-provider-panos#223]
Trying to use username/pw auth from terraform docs. Appears broken in build

```
user $ go build commit.go
# command-line-arguments
./commit.go:116:22: too many arguments in call to fw.Client.Commit
	have (string, nil, bool, bool, bool, bool)
	want (string, bool, bool, bool, bool)
```

**Comment by shinmog** [comment]
`Commit()` was updated to include support for partial commits (commit just the config changes by specific admins).  If you're getting this error, you need to update your version of `pango` so that the function signature matches.

**Comment by akingscote** [comment]
@shinmog What version do i need?
```
go get github.com/PaloAltoNetworks/pango
```
And then tried to run the commit code as per the terraform documentation but am getting the same error as @stobias123

**Comment by akingscote** [comment]
Found your example commit test file and it seems to get further. 
```
package main

import (
	"flag"
	"log"
	"strings"

	"github.com/PaloAltoNetworks/pango"
	"github.com/PaloAltoNetworks/pango/commit"
)

func main() {
	var (
		err                                                      error
		configFile, hostname, username, password, apiKey, admins string
		edan, eso, epao, force                                   bool
		jobId                                                    uint
	)

	log.SetFlags(log.Ldate | log.Ltime | log.Lmicroseconds)

	flag.StringVar(&configFile, "config", "", "JSON config file with panos connection info")
	flag.StringVar(&hostname, "host", "", "PAN-OS hostname")
	flag.StringVar(&username, "user", "", "PAN-OS username")
	flag.StringVar(&password, "pass", "", "PAN-OS password")
	flag.StringVar(&apiKey, "key", "", "PAN-OS API key")
	flag.StringVar(&admins, "admins", "", "CSV of specific admins for partial config commit")
	flag.BoolVar(&edan, "exclude-device-and-network", false, "Exclude device and network")
	flag.BoolVar(&eso, "exclude-shared-objects", false, "Exclude shared objects")
	flag.BoolVar(&epao, "exclude-policy-and-objects", false, "Exclude policy and objects")
	flag.BoolVar(&force, "force", false, "Force a commit even if one isn't needed")
	flag.Parse()

	// Connect to the firewall.
	fw := &pango.Firewall{Client: pango.Client{
		Hostname: hostname,
		Username: username,
		Password: password,
		ApiKey:   apiKey,
		Logging:  pango.LogOp | pango.LogAction,
	}}
	if err = fw.InitializeUsing(configFile, true); err != nil {
		log.Fatalf("Failed: %s", err)
	}

	// Build the commit to be performed.
	cmd := commit.FirewallCommit{
		Description:             flag.Arg(0),
		ExcludeDeviceAndNetwork: edan,
		ExcludeSharedObjects:    eso,
		ExcludePolicyAndObjects: epao,
		Force:                   force,
	}
	admins = strings.TrimSpace(admins)
	if admins != "" {
		cmd.Admins = strings.Split(admins, ",")
	}

	// Perform the commit
	jobId, _, err = fw.Commit(cmd, "", nil)
	if err != nil {
		log.Fatalf("Error in commit: %s", err)
	} else if jobId == 0 {
		log.Printf("No commit needed")
	} else if err = fw.WaitForJob(jobId, nil); err != nil {
		log.Printf("Error in commit: %s", err)
	} else {
		log.Printf("Committed config successfully")
	}
}
```

```
╰─ go run commitPanOS.go "my commit"
2020/06/16 13:47:24.962958 (op) show system info
2020/06/16 13:47:25.664222 (op) waiting for job 3
2020/06/16 13:47:36.225953 (op) job 3: 100 percent complete
2020/06/16 13:47:36.226975 Error in commit: Can't get vr  id(Module: dhcpd) | Commit failed
```
Not sure if the commit has actually failed or not. 
Can you please update the terraform documentation

**Comment by shinmog** [comment]
@stobias123 @akingscote 

Yeah, I'll be updating the docs with the updated script in the next release of the provider.

Just as an aside for anyone else looking at this thread, I've added a `time.Duration` param to `WaitForJob` so the above script is out of date now.  For the immediate future, please just grab the following script and replace `Example_firewallCommit()` with `main()`:

https://github.com/PaloAltoNetworks/pango/blob/master/example_firewall_commit_test.go

**Comment by jontreynes** [comment]
@shinmog also need to change line one's pango_test to main

**Comment by jontreynes** [comment]
@shinmog I'm having issue with the commit code you provided. I'm getting this error

Error in commit: Error unmarshaling into provided interface: expected element type <response> but have <HTML>

Do you know what the issue is?

**Comment by shinmog** [comment]
@jontreynes 

I do not know how you could get that error....  Is there an HTTP proxy between you and the firewall?  Is it giving you all of the HTML that is coming back from the firewall?  If not, can you update the script to get the returned HTML?  Maybe there's a clue in that.

You want to add this line before the `jobId, _, err = fw.Commit(cmd, "", nil)` line:

```go
fw.Logging |= pango.LogReceive
```

This will make the commit very noisy, but it may give some idea what's happening...

**Comment by jontreynes** [comment]
@shinmog 

I have not been able to reproduce the error I was getting. There is no proxy in between. Thank you for your help. The logging shows I am getting this type of response back on each response

```
Response = <response status="success"><result><job><tenq>2021/01/15 06:49:08</tenq><tdeq>06:49:08</tdeq><id>54</id><user>***</user><type>Commit</type><status>FIN</status><queued>NO</queued><stoppable>no</stoppable><result>OK</result><tfin>06:49:30</tfin><description>Sha of commit djshffdjshkjsdhkfjhsdkfhke</description><positionInQ>0</positionInQ><progress>100</progress><details><line>Configuration committed successfully</line></details><warnings></warnings></job></result></response>
```

**Comment by shinmog** [comment]
The commit documentation is updated in v1.7.0 which is being built now.

@jontreynes - If this continues to be an issue for you, please open a separate github issue.
