### ISSUE TITLE
Feature Request: Objects > Security Profiles

### ISSUE THREAD

**Issue by cmptscpeacock** [PaloAltoNetworks/terraform-provider-panos#226]
Request to create a provider to create Security Profile Objects as defined below (taken from GUI):

Objects > Security Profiles:

- Antivirus
- Anti-Spyware
- Vulnerability Protection
- URL Filtering
- File Blocking
- WildFire Analysis
- Data Filtering
- DoS Protection

Reference:

https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/policy/security-profiles.html

**Comment by shinmog** [comment]
Added in v1.7.0
