### ISSUE TITLE
Leveraging PAN pre-defined objects

### ISSUE THREAD

**Issue by nilknarfgnow** [PaloAltoNetworks/terraform-provider-panos#23]
The PAN pre-defined service objects should be referenced via TF data objects, such that I can utilize them in my TF files. For example, SSH is already defined as an application; however, I need a way to reference it in a security policy. All customers will eventually want to consume this data, so if there was a .tf file we could all download that contained all of the objects, that would be awesome. As services change or get added with major releases, they could be updated here, and people could use the corresponding version.

**Comment by shinmog** [comment]
Added some resources to pull / discover predefined PAN-OS config in the 1.7.0 provider, so I'm going to close this out for now.  If there is a specific predefined config that you want, please open a github issue for it so it can be tracked / addressed.
