### ISSUE TITLE
Add LACP, High Availability Options, and LLDP settings to panos_aggregate_interface.

### ISSUE THREAD

**Issue by 5mzJyf6m** [PaloAltoNetworks/terraform-provider-panos#230]
Hello,

Trying to manage aggregate interfaces but it is removing the LACP config from the interface. Please add these additional settings to the provider for panos for LACP, High Availability Options, and LLDP. These are found in the LACP and Advanced tabs of the Interface configuration in panos v9.0.
https://www.terraform.io/docs/providers/panos/r/aggregate_interface.html

Thank you.

**Comment by shinmog** [comment]
Will add this to the next provider release

**Comment by shinmog** [comment]
Added in v1.7.0
