### ISSUE TITLE
Feature Request: Add ECMP Configuration option for the Virtual Router

### ISSUE THREAD

**Issue by mpoletaev** [PaloAltoNetworks/terraform-provider-panos#235]
https://www.terraform.io/docs/providers/panos/r/panorama_virtual_router.html

Existing Terraform Resource for the virtual router doesn't have arguments to enable ECMP on the Virtual Router. 

![image](https://user-images.githubusercontent.com/47868022/79146957-2e601480-7d91-11ea-886d-1e03f8cbbbc0.png)

**Comment by shinmog** [comment]
Added in v1.7.0
