### ISSUE TITLE
panorama_zone documentation missing

### ISSUE THREAD

**Issue by salsop** [PaloAltoNetworks/terraform-provider-panos#240]
## Documentation link

https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/panorama_zone
https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/panorama_zone_entry

## Describe the problem

There doesn't seem to be any usage instructions on this object

## Suggested fix

There seems to be the documentation on the panos_zone objects, could we update?

**Comment by shinmog** [comment]
Fixed this in the new docs.  Closing.
