### ISSUE TITLE
PANOS Administrative Tag Colors

### ISSUE THREAD

**Issue by salsop** [PaloAltoNetworks/terraform-provider-panos#241]
## Documentation link

https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/panorama_administrative_tag

## Describe the problem

Can we detail what color the various color1, color2 etc colours are?

## Suggested fix

Please can we document this?

**Comment by salsop** [comment]
Color1 - Red
Color2 - ????
Color3 - Blue
Color4 - Yellow
Color5 - Copper
Color6 - Orange
Color7 - Purple
Color8 - Gray
Color9 - Light Green
Color10 - Cyan
Color11 - Light Gray
Color12 - Blue Gray
Color13 - Lime

**Comment by shinmog** [comment]
Fixed this in the docs, closing this out.
