### ISSUE TITLE
Next Release:  1.7.0

### ISSUE THREAD

**Issue by shinmog** [PaloAltoNetworks/terraform-provider-panos#248]
New Resources:

- Antivirus security profile
- Anti-Spyware security profile
- Vulnerability protection security profile
- URL filtering security profile
- File blocking security profile
- Wildfire analysis security profile
- Data filtering security profile
- Dos protection security profile
- ARP config
- OSPF support
- Dynamic user group
- (Panorama) Device group hierarchy (set device group parent)
- (Panorama) VM auth key
- (userid) tag ip
- (userid) tag user
- (userid) user login

Additional Functionality to Existing Resources:
- Add ECMP to virtual router config
- Add LACP, HA, and LLDP params to ethernet interfaces and aggregate ethernet interfaces
- Graceful erroring when using Panorama resources against firewalls and vice versa

**Comment by wolffberg** [comment]
Any update on when this will be added? The ECMP functionality is highly anticipated 🚀

**Comment by shinmog** [comment]
Should be two days from now, just have 3 sections left and a mountain of documentation...

**Comment by shinmog** [comment]
v1.7.0 is now released!
