### ISSUE TITLE
VM information sources

### ISSUE THREAD

**Issue by stobias123** [PaloAltoNetworks/terraform-provider-panos#281]
Would love to be able to create VM information sources as described here -> https://docs.paloaltonetworks.com/vm-series/8-1/vm-series-deployment/set-up-the-vm-series-firewall-on-aws/use-case-use-dynamic-address-groups-to-secure-new-ec2-instances-within-the-vpc

Kind of breaks the cloud native flow if we now have to go manually add this to all our firewalls.

**Comment by shinmog** [comment]
Using VM Information Sources seems to be sunsetted by using the AWS plugin on Panorama:

https://docs.paloaltonetworks.com/vm-series/8-1/vm-series-deployment/set-up-the-vm-series-firewall-on-aws/about-aws-vm-monitoring/set-up-vm-monitoring-on-aws.html#id187QKN00KVU

In light of this, do you still need a resource for VM Information Sources?

**Comment by stobias123** [comment]
It doesn't look like you can't configure the aws plugin from the terraform provider... so the same problem exists, just in a different spot.

**Comment by shinmog** [comment]
@stobias123 

If you could get one or the other, which do you want?
