### ISSUE TITLE
Custom URL filtering Category 

### ISSUE THREAD

**Issue by ba31** [PaloAltoNetworks/terraform-provider-panos#308]
### Is your feature request related to a problem?
Yes, there is a number of requests where specific URL categories need to allow from a specific source but it seems like terraform does not support it. Ansible has supported this via "panos_custom_url_category" 

### Describe the solution you'd like
Terraform should allow creating custom URL categories which should have allowed type available either "category Match" or "URL List"

### Describe alternatives you've considered
Ansible "panos_custom_url_category" module used to cover this requirement.

**Comment by shinmog** [comment]
This is a dupe of #157 which will be coming out by the end of December.
