### ISSUE TITLE
rulebase "pre-rulebase" requires a specific device group, not "shared"

### ISSUE THREAD

**Issue by ba31** [PaloAltoNetworks/terraform-provider-panos#314]
## Describe the bug

terraform provider 1.8.3 was allowed to deploy the pre-rulebase and post-rulebase inside "shared" device group but as soon as upgrade 1.9.0 the terraform reported the following error.

![image](https://user-images.githubusercontent.com/41516771/148571635-a42228d5-491c-4d9c-b6db-4ebada4ff823.png)

## Expected behavior

Terraform provider 1.9.0 should allow deploying the rulebase in the "shared" device group

## Current behavior

Only allowed to deploy the rulebase in the user-defined device group

## Possible solution

Only allowed to deploy the rulebase in the user-defined device group

**Comment by shinmog** [comment]
Well, I just logged in to a 10.1 Panorama to verify and it looks like /config/shared/pre-rulebase and /config/shared/post-rulebase both exist, while /config/shared/rulebase (which used to be the only option) does not......  So I guess this changed at some point..?

I'll put out a new release today, but I have to track down when this changed.

**Comment by ba31** [comment]
I am using 10.1.3 and checked xpath too and seems its allow to use . 
Thank you for quick resolve

**Comment by shinmog** [comment]
I checked as far back as 7.1, and it seems like /config/shared/rulebase never existed, it's always been /config/shared/pre-rulebase and /config/shared/post-rulebase...

So I'm just unconditionally lifting this restriction, new release should be out in 10-15min or so.

**Comment by shinmog** [comment]
Fixed in v1.9.1

**Comment by ba31** [comment]
worked like a charm . Thank you
