### ISSUE TITLE
Terraform init issue with Docker

### ISSUE THREAD

**Issue by Montana** [PaloAltoNetworks/terraform-provider-panos#318]
Hey PAN,

I accidentally posted this in the wrong area the first time, but was informed this was the right area! 

I've ran `type=version` and requested the version type to show in a verbose esque manner on PAN-OS. I've been setting this up in conjunction with HashiCorp Terraform. It currently looks like this:

```javascript
resource "panos_dynamic_user_group" "example" {
    name = "montanatest1"
    description = "PAN and Terraform"
    filter = "'orange'"
}
```

This is mainly using `panos_dynamic_user_group`, what I want to do is set up another machine do some flavor of a cron job and or a cron table, which I could SSH into the appliance and reboot it.

Is this feasible?

Thank you so much!
Cheers,
Montana Mendy

**Comment by shinmog** [comment]
Little confused what you're asking.

Are you asking if there is a `panos` resource that reboots the NGFW / Panorama?

**Comment by shinmog** [comment]
So that restarts the management plane, which is different than restarting the whole box itself.

But either way, there is no resource that restarts PAN-OS or the management plane right now.

**Comment by Montana** [comment]
Thank you for clearing this up @shinmog, 

Have a wonderful weekend.
