### ISSUE TITLE
Cannot use resource type panos_address_objects

### ISSUE THREAD

**Issue by dersoi** [PaloAltoNetworks/terraform-provider-panos#322]
## Describe the bug
Trying to use the resource panos_address_objects generates the error 
_The provider provider.panos does not support resource type "panos_address_objects"._ 

## Expected behavior
Address objects should be planned as per the documentation: 
[https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/address_objects](https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/address_objects)

## Current behavior

Trying to generate a plan with the command  `terraform plan` generates the error 
_The provider provider.panos does not support resource type "panos_address_objects"._ 

## Steps to reproduce

[https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/address_objects](https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/address_objects)
Simply follow the documentation and try to create resources (event one does not work):

1.
~~~hcl
resource "panos_address_objects" "address" { 
  device_group = "DG1_GLOBAL" 
  object { 
    name  = "test" 
    value = "10.0.0.3/32" 
    type  = "ip-netmask" 
  } 
} 
~~~
2. Run the command `terraform plan`
3. Get the error _The provider provider.panos does not support resource type "panos_address_objects"._ 

## Context
I am currently using panos_address_object (no s) as a resource, but as wer are getting timeouts from the API, I wanted to try this. 

## Your Environment

~~~cli
$ terraform -version 

Terraform v0.14.5 

+ provider registry.terraform.io/hashicorp/null v3.1.0 

+ provider registry.terraform.io/paloaltonetworks/panos v1.9.2 
~~~

**Comment by shinmog** [comment]
`panos_address_objects` is present in v1.10.0, seems you're on v1.9.2.

**Comment by dersoi** [comment]
Right you are! I did not even think to check for an upgrade has the repo had been silent for quit a long time before the last one. 

I offer to add clear mentions needed version when a new feature is added.  #323
