### ISSUE TITLE
Adding lifecycle meta-argument to examples

### ISSUE THREAD

**Issue by cdot65** [PaloAltoNetworks/terraform-provider-panos#355]
## Documentation link

Any documentation page with an example of a resource declared for this provider.

## Describe the problem

This is a request for improvement to the documentation, where all examples of resources will need to be updated to include a instance of Terraform's `lifecycle` meta-argument.

## Suggested fix

Append the following to each example of a resource

```hcl
    lifecycle {
        create_before_destroy = true
    }
```

**Comment by shinmog** [comment]
Fixed by #356
