### ISSUE TITLE
SSL Certificate Support

### ISSUE THREAD

**Issue by freimer** [PaloAltoNetworks/terraform-provider-panos#4]
Please add support to manage certificates on the Device tab for a particular Template through Panorama.  For certificates with the private key, please do not store the key in the state file, or if you do make sure it is the encrypted key, and do not store the password.

**Comment by shinmog** [comment]
I don't have any Template support for Panorama just yet, which would need to happen before I could add certificate management in.  Part of this is because I'm unclear on what kind of Template support Terraform users would be looking for.

As an example, are you looking to create/update/delete certificates using Panorama..?  Or do you just need the ability for Terraform to let you put devices (and specific vsys) into an existing Template (aka - `panos_panorama_device_group_entry`, but for templates)?

**Comment by shinmog** [comment]
Panorama support has been added as of provider version 1.1.0, so I'm getting closer to being able to add support for this.  I would still need clarification on what functionality you're looking for from the resource, @freimer

**Comment by freimer** [comment]
Sorry, I've been busy ;-).  Great work on the panorama support, by the way.  I'm actually looking for both, but really wanted to focus on the ability to create/update/delete SSL certificates using Panorama.

**Comment by shinmog** [comment]
@freimer 
Both templates and template stacks have now been added to the provider (version 1.4.0).

**Comment by shinmog** [comment]
@freimer 

Hi again - I wanted to ask you what certificate operations you're after.  Is it that you have certs stored locally and you want to upload that and the private key files to the firewall / Panorama?  Are you most interested in using the "Generate" functionality to create your own certs?  Something else?

I'm wondering if I can start covering certs bit by bit, but if I did, I'd want to make sure I'm getting the most important functionality first.

**Comment by shinmog** [comment]
@freimer 
If this applies to you, I'm looking at possibly doing a Let's Encrypt integration.  If this is something that you're interested in, could you please chime in on this discussion:

https://live.paloaltonetworks.com/t5/Automation-API-Discussions/LetsEncrypt-integration/m-p/224315

**Comment by mikebranstein** [comment]
A good starting point is to allow the import of certificates - public and private key pairs. This would allow the configuration of SSL Decryption without manual intervention.
