### ISSUE TITLE
Missing resources based on provider version 1.11.1

### ISSUE THREAD

**Issue by Justin-Schoenaker** [PaloAltoNetworks/terraform-provider-panos#450]
In the new version I'm missing a lot of resources like creating tunnel interfaces, ipsec and ike config. 
Will this be added in future releases?

And based on the new routing engine "Advanced Routing", is this logical router something that can be expected in some future releases?

### Additional context

I tried to rebuild my terraform script to create a site to site vpn with the Advanced routing engine enabled. I saw the new version but couldn't find the resources. 

I tried the script with version 1.11.1 and saw Panorama was abled to process the virtual router config, and pushed this to the logical router on the firewall.
But it should in panorama also be present in te logical router config of course.

**Comment by timja** [comment]
It's the default version on the terraform docs page: https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs

Not ideal to have an alpha version that isn't recommended to show as the default
