### ISSUE TITLE
Feature Request: Provider needed for security profiles

### ISSUE THREAD

**Issue by crispyblock** [PaloAltoNetworks/terraform-provider-panos#77]
I want to be able to configure URL filtering, AV, and other items in a security profile.

**Comment by erikpaasonen** [comment]
I think this refers to a new Terraform resource within the `panos` provider.

**Comment by shinmog** [comment]
@crispyblock @erikpaasonen 
Are any of the profiles more important than others for Terraform to be able to manage?

**Comment by tgm4883** [comment]
I'd say they are all pretty important, but if I had to rank them it would be

Antivirus
Anti-Spyware
Vulnerability Protection
File Blocking
WildFire Analysis
DoS Protection
URL Filtering
Data Filtering

Also, I'd like to be able to configure the "Security Profile Groups" via terraform

**Comment by shinmog** [comment]
Added in v1.7.0
