### ISSUE TITLE
Device Groups

### ISSUE THREAD

**Issue by kerry-knight** [PaloAltoNetworks/terraform-provider-panos#80]
In Panorama,  I can create Address Groups,  where the members are simply IP addresses. It seems that in Terraform, it errors on this, and requires you building individual Address objects for each member.

**Comment by shinmog** [comment]
@kerry-knight 

Can you sanity check something for me, as I'm working in a test environment:  does your Panorama GUI allow you to type in a freeform IP address into an address group's static definition?  Mine doesn't, so I'm wondering if this is a Panorama design decision.

**Comment by shinmog** [comment]
@kerry-knight 

Ok, I just tried with 8.0.3-h4 and 7.1.9 (please don't judge me, lol).  None of these will allow me to add a free-form IP address, but your Panorama is allowing this, where as the Terraform provider is failing..?

**Comment by shinmog** [comment]
Seems to not be an issue anymore, so closing this issue.
